import { NextPage } from 'next';
import Head from 'next/head';
import { Map } from '../components/atoms/Map/Map';
import { createSuppliersApi } from '../api/suppliers-api';
import { useToggle } from 'react-use';
import { CreateSupplierModal } from '../components/organisms/CreateSupplierModal/CreateSupplierModal';
import { Fragment, useMemo } from 'react';
import { locale } from '../translations';
import { useSet } from '../hooks/useSet/useSet';
import { updateSupplierSchema } from '../server/suppliers/validation';
import Link from 'next/link';
import { EditableInput } from '../components/atoms/EditableInput/EditableInput';

const Suppliers: NextPage = () => {
	const suppliersApi = createSuppliersApi();
	const { suppliers } = suppliersApi.getAll();
	const { onUpdateById } = suppliersApi.updateById();
	const [isOpen, toggleIsOpen] = useToggle(false);
	const [selectedSupplierIds, actions] = useSet<string>();
	const { onDeleteByIds } = suppliersApi.deleteByIds<Array<string>>(
		actions.arrayToSet,
	);
	const onSelectSupplierId = (id: string) => () =>
		actions.toggle(id);
	const allSupplierIds = new Set(
		suppliers?.map((supplier) => supplier.id) ?? [],
	);
	const onSelectAllSupplierIds = () =>
		actions.toggleAll(allSupplierIds);
	const onDeleteSelectedSuppliers = () => {
		onDeleteByIds({
			ids: actions.array(),
		});
		actions.clear();
	};
	const isAllSupplierIdsSelected = useMemo(
		() =>
			[...allSupplierIds].every((id) =>
				selectedSupplierIds.has(id),
			),
		[selectedSupplierIds, allSupplierIds],
	);

	return (
		<div>
			<Head>
				<title>Danon Ordering System</title>
				<meta
					name='description'
					content='Generated by create-t3-app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='container pt-[7vh] min-h-screen p-2 mx-auto'>
				<div className={`flex justify-between mb-2`}>
					<div className={`space-x-2`}>
						<Link href={'/'} passHref>
							<a className={'btn'}>
								{locale.he.products}
							</a>
						</Link>
						<CreateSupplierModal
							isOpen={isOpen}
							onOpen={toggleIsOpen}
						/>
						<button
							disabled={
								!suppliers?.length ||
								!selectedSupplierIds.size
							}
							className={'btn '}
							onClick={onDeleteSelectedSuppliers}
						>
							{locale.he.delete}
						</button>
					</div>
					<div className={`flex space-x-2`}>
						<Link href={`/api/auth/signout`}>
							<a className={`btn`}>
								{locale.he.signOut}
							</a>
						</Link>
					</div>
				</div>
				<ul
					className={`menu p-1 border border-neutral/25 rounded`}
				>
					<li
						className={`menu-title text-center font-bold`}
					>
						{locale.he.suppliers}
					</li>
					<li>
						<div
							className={`hover:!bg-base-100 cursor-auto`}
						>
							<input
								type={`checkbox`}
								className={`checkbox ml-auto`}
								onChange={onSelectAllSupplierIds}
								checked={isAllSupplierIdsSelected}
							/>
						</div>
					</li>
					<Map
						items={suppliers ?? []}
						render={({ id, name, email }) => (
							<Fragment key={id}>
								<li className={`hover-bordered`}>
									<div
										className={`flex justify-between active:bg-neutral-focus/10 active:text-base-content`}
									>
										<div>
											<div>
												Name:{' '}
												<EditableInput
													type={`name`}
													initialValue={
														name
													}
													onEdit={async (
														value,
													) => {
														const {
															name,
														} = updateSupplierSchema
															.pick({
																name: true,
															})
															.parse({
																name: value,
															});

														await onUpdateById(
															{
																id,
																name,
															},
														);
													}}
												/>
											</div>
											<div>
												Email:{' '}
												<EditableInput
													initialValue={
														email
													}
													onEdit={async (
														value,
													) => {
														const {
															email,
														} = updateSupplierSchema
															.pick({
																email: true,
															})
															.parse({
																email: value,
															});

														await onUpdateById(
															{
																id,
																email,
															},
														);
													}}
													type={`email`}
												/>
											</div>
										</div>
										<input
											type={`checkbox`}
											className={`checkbox`}
											onChange={onSelectSupplierId(
												id,
											)}
											checked={selectedSupplierIds.has(
												id,
											)}
										/>
									</div>
								</li>
								<div className={`divider p-1`} />
							</Fragment>
						)}
					/>
				</ul>
			</main>
		</div>
	);
};

export default Suppliers;
